language: node_js
env:
  - TRAVIS_CI=true
  # https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
  - CXX="g++-4.8" CC="gcc-4.8"
node_js:
  - 7
addons:
  firefox: latest
cache:
  yarn: true
before_install:
  - npm install -g codecov
before_script:
  # http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
after_script:
  - codecov
