language: node_js
env:
- TRAVIS_CI=true CXX="g++-4.8" CC="gcc-4.8"
node_js:
- 7
addons:
  firefox: latest
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  yarn: true
before_install:
- npm install -g codecov
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
after_script:
- codecov
notifications:
  slack:
    secure: byMSN3DSO4JZ/jK8y4QYFftv8eWdagBS0tpGJmeLN6gtzGIYeZuTLZ/1I1dMwJmkZrZdSx03N0UUkon/BtZXtOvVEpBfY2t6BO2Zt+LeztZjUpfQ+th2BiIiYvwIH4mcZIV+Y52Ceywehv0txw3GCj9WtUGudS7a1M56XFeCjdMdr3vv5u4tB7PZZRKjJSWkaTezvBH6Vi2Nac7wAlYHHXMYc3+siMK0q9miwqBNMCgvA3uQPEUrSHFLgg8PFtu49Sgs7iGZ10PoxaziIgX6gpqRiD8nOHKpT7KAHOvEEQrwGGVS/UZcgyDnCat+oIqJxIMQqdN67xvCdlTv2lqmxTEKWEtH5V5VirS5gbCTaQQLPS2PAXtQaPB0mWcYtt6NsnJr/J3iZoFh7Sf+Gwt+0ItnP3970KfJKMwx0BA+Ee/DmOYRAgAMHPzTYIM29RL2EK+ImsqlK3e8K38m2MLIaTGCj5uReWgDzRsIgXRG2uUi8MH9AilB46Aomrn9QxhOSpN/AyaBg0o61qiEA/r0zjkrNlTiekRX+t2RVjTZs1Z2U4cd1ZTNDa9acimUKznmnADySLiCKxJOEHiwNHyCuEk++K8UMIv5V4AP3K2wYIfHh7Bx6J4PSgi7wDT60K4bKDTjpBDPrhgLfdPn/RCP/h3OZLy04hcDC72UV/QrjDg=
before_deploy:
  - npm run build
  - tar cvf dist.tar.gz dist
deploy:
  provider: releases
  api_key:
    secure: kIODd/DWUeOAtX+ANo5gUgjicYVDhDfNhIna71PulQPeJRVV0fAOkAG2T2+H8tTW2eRkf01WcRaQqZ/gaJDaq56tyNNnver2I8CqlSYmLQv3tm0Ah+CSJLxF8Ng1CTZh+D66dna/n8nq3a1/P9C8CVzcpwco/i9+dKBNHebLAPc7m5uEaNNgp0jV86xvDaBqgWJhyYPwGP1Moh8dGj1E5HT62yF8nyQB1qDQLQqFQLfYoLnMHaE9t4bLLzvSV7v4YwJC1laPPoJ3yqr/3DYaSsT2RIC+zm0b6+ffbEkwFKQCuT1RGYr9Qg6idh3FpZMOCGq+5D96EqiD4XUrD/iewPiuUTKkWnrfWUsSR/XjVzx2jFNRKOOfFAfwbkWT1lvxmMN60tUxNuXLkUx+fX9VIKViGHnwBqK/jCBvqmrxQCjnKXpqxY5LsewqOxrg/07/8MZ/CmgbBGnXUFgMXg08cFMdjWnhhHSPuy7budFxRIRmu2oPGl6AbV3UXK84s/+StykHnOzF60qxkEtUAA9GCTp8bhGCx8KtI1Glm5PUGXm31Hx/LJ76E4yxj/JaES/FNgBqqerEZScVJR/5jxFC5Y2H8bxVmvZzKAACvA3qZoZ2jNsSUlN70saztvoQnPomWTM4pvYtIVXqTz6d5LI/8h6IY7Oz8r4ywOxGTG07/4w=
  file: dist.tar.gz
  on:
    repo: foodsharing-dev/foodsharing-light
